### ISSUE TITLE
Symbol seems to be handled twice.

### ISSUE THREAD

**Issue by urstruktur** [krachzack/fernspielapparat#18]
The transition from "quiet" state to "talk" state.

```
initial: ec1876ef-6181-4079-99f6-c1ed7f40f9de
states:
  05e2f421-83a8-40e2-80ee-f4d068679969:
    name: Pause
    description: Does nothing for a while and rings again afterwards
    sounds: []
    ring: 0
    terminal: false
  ec1876ef-6181-4079-99f6-c1ed7f40f9de:
    name: Ring
    description: ""
    sounds: []
    ring: 0.5
    terminal: false
  9a665704-6a15-4feb-b609-fb98917bf5c6:
    name: Introduce
    description: ""
    sounds:
      - 89119a50-910c-4baf-85c3-686382af5f9b
    ring: 0
    terminal: false
  debb3230-e6fe-4aee-b231-63ca2c125d59:
    id: debb3230-e6fe-4aee-b231-63ca2c125d59
    name: talk
    description: ""
    sounds:
      - 55f81463-3179-486b-8900-36ca37c46bff
    ring: 0
    terminal: false
  bc6695f9-97eb-4078-a494-cd25e3ca276f:
    id: bc6695f9-97eb-4078-a494-cd25e3ca276f
    name: quiet
    description: ""
    sounds: []
    ring: 0
    terminal: false
transitions:
  any:
    pick_up: 9a665704-6a15-4feb-b609-fb98917bf5c6
    hang_up: 05e2f421-83a8-40e2-80ee-f4d068679969
  05e2f421-83a8-40e2-80ee-f4d068679969:
    timeout:
      after: 60
      to: ec1876ef-6181-4079-99f6-c1ed7f40f9de
  ec1876ef-6181-4079-99f6-c1ed7f40f9de:
    timeout:
      after: 1.5
      to: ec1876ef-6181-4079-99f6-c1ed7f40f9de
  9a665704-6a15-4feb-b609-fb98917bf5c6:
    timeout:
      after: 5
      to: 9a665704-6a15-4feb-b609-fb98917bf5c6
    dial:
      "1": debb3230-e6fe-4aee-b231-63ca2c125d59
  debb3230-e6fe-4aee-b231-63ca2c125d59:
    timeout:
      to: bc6695f9-97eb-4078-a494-cd25e3ca276f
      after: 0
    dial:
      "1": bc6695f9-97eb-4078-a494-cd25e3ca276f
  bc6695f9-97eb-4078-a494-cd25e3ca276f:
    dial:
      "1": debb3230-e6fe-4aee-b231-63ca2c125d59
vendor:
  fernspieleditor:
    version: 1
    focusedStateId: debb3230-e6fe-4aee-b231-63ca2c125d59
    extensionProperties:
      states:
        any:
          network:
            position:
              x: 100
              y: 100
        05e2f421-83a8-40e2-80ee-f4d068679969:
          network:
            position:
              x: 300
              y: 100
        ec1876ef-6181-4079-99f6-c1ed7f40f9de:
          network:
            position:
              x: 500
              y: 100
        9a665704-6a15-4feb-b609-fb98917bf5c6:
          network:
            position:
              x: 225
              y: 274
        debb3230-e6fe-4aee-b231-63ca2c125d59:
          network:
            position:
              x: 487
              y: 273
        bc6695f9-97eb-4078-a494-cd25e3ca276f:
          network:
            position:
              x: 311
              y: 504
sounds:
  89119a50-910c-4baf-85c3-686382af5f9b:
    name: Introduction
    loop: true
    speech: Hallo du! Ich bin's, dein Fernseher. Das Konsumieren von Medien über
      Jahrzehnte hat mir ein Bewusstsein beschert. Willst du mein Freund sein?
    volume: 0.9
    backoff: 0.2
  55f81463-3179-486b-8900-36ca37c46bff:
    name: talk1
    loop: false
    speech: Ich habe Hunger.
    volume: 0
    backoff: 0
```
